#!/bin/bash

# Handle Lambda Function Update Conflict
# This script helps resolve the ResourceConflictException when updating Lambda function

set -e

echo "🔧 Handling Lambda Function Update Conflict"
echo "=========================================="
echo ""

echo "📋 Issue: Lambda function is being updated by another process"
echo ""

echo "🔍 Step 1: Check Lambda Function Status"
echo "======================================"
echo ""
echo "1. Go to AWS Lambda Console:"
echo "   https://console.aws.amazon.com/lambda/home?region=us-west-2#/functions/enhanced-auto-remediation-lambda-arm64"
echo ""
echo "2. Check the function status in the console"
echo "3. Look for any ongoing updates or deployments"
echo ""

echo "⏳ Step 2: Wait for Current Update to Complete"
echo "============================================="
echo ""
echo "The Lambda function is currently being updated. You need to wait for the current update to complete."
echo ""
echo "Expected wait time: 2-5 minutes"
echo ""

echo "🔄 Step 3: Re-run GitHub Actions Workflow"
echo "========================================"
echo ""
echo "After the Lambda function update completes:"
echo ""
echo "1. Go to GitHub Actions: https://github.com/Yayati-tech/Agent-Hubble/actions"
echo "2. Find the failed workflow run"
echo "3. Click 'Re-run jobs' or 'Re-run all jobs'"
echo "4. Monitor the workflow execution"
echo ""

echo "🔍 Step 4: Check for Concurrent Updates"
echo "======================================"
echo ""
echo "To prevent this issue in the future:"
echo ""
echo "1. Ensure only one deployment is running at a time"
echo "2. Wait for previous deployments to complete"
echo "3. Check Lambda function status before starting new deployment"
echo ""

echo "🧪 Step 5: Manual Verification"
echo "============================="
echo ""
echo "You can manually check the Lambda function status using AWS CLI:"
echo ""
echo "aws lambda get-function --function-name enhanced-auto-remediation-lambda-arm64 --region us-west-2"
echo ""

echo "🚨 Alternative Solutions:"
echo "======================="
echo ""
echo "If the issue persists:"
echo ""
echo "1. **Wait and Retry**: Wait 5-10 minutes and re-run the workflow"
echo "2. **Check CloudWatch Logs**: Look for any ongoing Lambda executions"
echo "3. **Manual Update**: Update the function manually in AWS Console"
echo "4. **Force Update**: Stop any ongoing Lambda executions"
echo ""

echo "📊 Expected Timeline:"
echo "==================="
echo ""
echo "⏱️  Current update completion: 2-5 minutes"
echo "🔄 Re-run workflow: After current update completes"
echo "✅ Total resolution time: 5-10 minutes"
echo ""

echo "🎯 Next Steps:"
echo "=============="
echo ""
echo "1. Wait for the current Lambda function update to complete"
echo "2. Re-run the GitHub Actions workflow"
echo "3. Monitor the deployment progress"
echo "4. Verify the Lambda function is updated successfully"
echo ""

echo "🔗 Useful Links:"
echo "================"
echo ""
echo "📋 AWS Lambda Console: https://console.aws.amazon.com/lambda/home?region=us-west-2#/functions/enhanced-auto-remediation-lambda-arm64"
echo "🔧 GitHub Actions: https://github.com/Yayati-tech/Agent-Hubble/actions"
echo "📊 CloudWatch Logs: https://console.aws.amazon.com/cloudwatch/home?region=us-west-2#logsV2:log-groups/log-group/$252Faws$252Flambda$252Fenhanced-auto-remediation-lambda-arm64"
echo "" 