#!/bin/bash

# Quick Lambda Function Status Check
# This script provides a simple way to check Lambda function status

echo "🔍 Quick Lambda Function Status Check"
echo "===================================="
echo ""

echo "📋 Current Status:"
echo "=================="
echo ""
echo "✅ IAM permissions are working (you got past the layer publishing step)"
echo "✅ Lambda layer 'cryptography-layer' was successfully published"
echo "🔄 Lambda function is currently being updated"
echo "⏳ Waiting for function update to complete..."
echo ""

echo "🔗 Check These Links:"
echo "===================="
echo ""
echo "1. **AWS Lambda Console**:"
echo "   https://console.aws.amazon.com/lambda/home?region=us-west-2#/functions/enhanced-auto-remediation-lambda-arm64"
echo ""
echo "2. **GitHub Actions**:"
echo "   https://github.com/Yayati-tech/Agent-Hubble/actions"
echo ""
echo "3. **CloudWatch Logs**:"
echo "   https://console.aws.amazon.com/cloudwatch/home?region=us-west-2#logsV2:log-groups/log-group/$252Faws$252Flambda$252Fenhanced-auto-remediation-lambda-arm64"
echo ""

echo "🎯 What to Look For:"
echo "==================="
echo ""
echo "In AWS Lambda Console:"
echo "• Function State: Should show 'Active' (not 'Updating')"
echo "• Last Update Status: Should show 'Successful' (not 'InProgress')"
echo "• No error messages in the console"
echo ""

echo "⏱️  Expected Timeline:"
echo "===================="
echo ""
echo "• Current wait time: 5-15 minutes total"
echo "• Check every 2-3 minutes"
echo "• Function should become available soon"
echo ""

echo "🔄 When Ready to Re-run:"
echo "======================="
echo ""
echo "1. Go to GitHub Actions: https://github.com/Yayati-tech/Agent-Hubble/actions"
echo "2. Find the failed workflow run"
echo "3. Click 'Re-run jobs' or 'Re-run all jobs'"
echo "4. Monitor the deployment progress"
echo ""

echo "💡 Status Indicators:"
echo "==================="
echo ""
echo "✅ READY: Function State = 'Active', Last Update Status = 'Successful'"
echo "⏳ WAITING: Last Update Status = 'InProgress' or 'Pending'"
echo "❌ ERROR: Function shows error messages or 'Failed' status"
echo ""

echo "🎉 Success Indicators:"
echo "===================="
echo ""
echo "• Lambda function state: 'Active'"
echo "• Last Update Status: 'Successful'"
echo "• cryptography-layer exists with versions"
echo "• No error messages in console"
echo "• GitHub Actions can be re-run successfully"
echo ""

echo "🔄 Run this script again in 2-3 minutes to check status"
echo "" 