name: Setup GitHub Secrets Guide

on:
  workflow_dispatch:

jobs:
  setup-guide:
    runs-on: ubuntu-latest
    
    steps:
    - name: Setup Guide
      run: |
        echo "🔧 GitHub Actions Setup Guide"
        echo "============================"
        echo ""
        echo "📋 Required GitHub Secrets:"
        echo ""
        echo "1. AWS_ACCESS_KEY_ID"
        echo "   - Go to AWS IAM Console"
        echo "   - Create a user with Lambda and CloudWatch permissions"
        echo "   - Add the Access Key ID as a secret"
        echo ""
        echo "2. AWS_SECRET_ACCESS_KEY"
        echo "   - Use the Secret Access Key from the same IAM user"
        echo "   - Add as a secret"
        echo ""
        echo "🔐 How to Add Secrets:"
        echo "1. Go to your GitHub repository"
        echo "2. Click Settings > Secrets and variables > Actions"
        echo "3. Click 'New repository secret'"
        echo "4. Add each secret with the exact names above"
        echo ""
        echo "📝 IAM Permissions Required:"
        echo "- lambda:UpdateFunctionCode"
        echo "- lambda:UpdateFunctionConfiguration"
        echo "- lambda:PublishLayerVersion"
        echo "- cloudwatch:PutDashboard"
        echo "- iam:PassRole (if using custom role)"
        echo ""
        echo "🚀 After adding secrets:"
        echo "1. Push changes to main branch, OR"
        echo "2. Go to Actions tab and run 'Deploy Security Hub Lambda' manually"
        echo ""
        echo "✅ The workflow will:"
        echo "- Build cryptography layer in Linux environment"
        echo "- Deploy Lambda function with the layer"
        echo "- Test the deployment"
        echo "- Create CloudWatch dashboard"
        echo "" 